### ISSUE TITLE
I've installed the voyager-extension, but how can I access the admin panel?

### ISSUE THREAD

**Issue by aymanalhattami** [MonstreX/voyager-extension#10]
In voyager I access the admin panel by using  http://127.0.0.1:8000/admin, but in voyager-extension I couldn't access the admin panel.

**I followed all these steps:**
Package installation
Via Composer

$ composer require monstrex/voyager-extension
Then run migrations:

$ php artisan migrate
Publish config if you need:

$ php artisan vendor:publish --provider="MonstreX\VoyagerExtension\VoyagerExtensionServiceProvider" --tag="config"
To use Image fields you need publish and migrate laravel-medialibrary resources

$ php artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="migrations"
$ php artisan migrate
Optional you may like to publish the config laravel-medialibrary as well

$ php artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="config"

**Comment by MonstreX** [comment]
Before using voyager-extension you should completely configure The Voyager. The voyager should works before you start using voyager-extension.

**Comment by muath-ye** [comment]
> Before using voyager-extension you should completely configure The Voyager. The voyager should works before you start using voyager-extension.

Does voyager-extension require a specific version of Voyager? if it requires, could you @MonstreX inform us, please!

**Comment by MonstreX** [comment]
It should work with "tcg/voyager": "1.4.*"
