### ISSUE TITLE
legacy_edit_add_bread breaks coordinates formfield

### ISSUE THREAD

**Issue by EmilioBravo** [MonstreX/voyager-extension#16]
Hi, thanks for this great package! I've found that using it with config legacy_edit_add_bread => false, wich is the default, breaks the coordinates formfield. 

![image](https://user-images.githubusercontent.com/544288/117876439-62965500-b271-11eb-80d2-305e52bba7fa.png)

**Comment by MonstreX** [comment]
Thank you for your report! I'll check it out as soon as I get free time.

**Comment by MonstreX** [comment]
I can't manage it directly, but you can fix it by copying the original coordinates.blade.php into your project folder - /resources/views/vendor/voyager/formfields/coordinates.blade.php.
then replace string:
```js
var gMapVm = new Vue({ el: '#coordinates-formfield' });
```
with:
```js
if (typeof gMapVm === 'undefined') {
    var gMapVm = new Vue({ el: '#coordinates-formfield' });
}
```
Then the field will works as supposed to.
It'll be added to the package docs.
