### ISSUE TITLE
Open to PR's

### ISSUE THREAD

**Issue by eddielee394** [MonstreX/voyager-extension#2]
Pretty cool voyager package.  Would you be open to any pull requests? I added a few conditions that make the `form_model` optional instead of required.  It also hides the `form` select input on the layout section for a given model, if the `form_model` json param isn't present in the bread options.  Currently I'm just extending the `AdvPageLayoutFormField` class to handle it, but figured it might be something to consider adding to the core package.  I also added an optional style param to the bread options for blocks, to give the user a bit more control over how the block select inputs are laid out on the add/edit view.

**Comment by MonstreX** [comment]
Thank you and thanks for your comment. Yep, I've got what you mean. I think it has to be included in the core functionality.

> Would you be open to any pull requests?

Yep, why not.
