### ISSUE TITLE
Voyager Custom views don't work with voyager-extension

### ISSUE THREAD

**Issue by sligregni** [MonstreX/voyager-extension#26]
Hello, 

I'm trying to use this great package in an existing project but it seems voyager-extension doesn't work properly with custom views and actions. 
Custom views and action followed the official documentation: https://voyager-docs.devdojo.com/customization/overriding-files

Problems encountered: 
- Browse views has the legacy appearance
- Clone action doesn't work (but it appears). 
- Save and Continue Editing and Save and Create New don't appear in edit-add views

Laravel Framework 7.30.4
Voyager              1.5.0

Have you any suggestion to have it sorted out? 

I'm not very skilled on Laravel, so sorry in advance if this is not a issue of the package!

Thanks a lot!

**Comment by MonstreX** [comment]
Hello.

There are some tricky things to implements extension on the voyager package. Sometimes it can't work properly as you supposed to. The recommened way to use voyager-extension - fresh installation laravel+voyager. However, you still can overriding Voyager and Voyager-Extension Views. There are two main points:
1) If you need overriade common Bread Views - copy the Voyager-Extension original views into /resources/views/vendor/**voyager-extension**/bread folder.
2) If you need override specific single bread model - copy the Voyager-Extension original views into /resources/views/vendor/**voyager**/<model slug> folder.

I hope it'll help you.

**Comment by sligregni** [comment]
Hello, 

thanks for the explanations. 

> If you need override specific single bread model - copy the Voyager-Extension original views into /resources/views/vendor/voyager/ folder.

This is the solution for me. I only need to implement my changes there. 

Simone
