### ISSUE TITLE
Overwrite the content of additional_css and additional_js

### ISSUE THREAD

**Issue by MariusRuix** [MonstreX/voyager-extension#27]
Overwrite the content of additional_css and additional_js, you should use something like array_merge, so as not to delete the existing data.

https://github.com/MonstreX/voyager-extension/blob/ce2672e5ec89be422ff96d75b96c3ec4ca681e99/src/VoyagerExtensionServiceProvider.php#L145

https://github.com/MonstreX/voyager-extension/blob/ce2672e5ec89be422ff96d75b96c3ec4ca681e99/src/VoyagerExtensionServiceProvider.php#L149

**Comment by MonstreX** [comment]
Yep. You are absolutely right. Will be fixed on the next release with:
```php
  Config::set(
      'voyager.additional_js',
      array_merge(config('voyager.additional_js'), [voyager_extension_asset('js/app.js')])
  );
```
Thank you for your help!
