### ISSUE TITLE
Does not work with medialibrary 9

### ISSUE THREAD

**Issue by mohammad6006** [MonstreX/voyager-extension#28]
Problem 1
    - Root composer.json requires monstrex/voyager-extension ^0.95.0 -> satisfiable by monstrex/voyager-extension[v0.95].
    - monstrex/voyager-extension v0.95 requires spatie/laravel-medialibrary ^8.00.0 -> found spatie/laravel-medialibrary[8.0.0, ..., v8.x-dev] but it conflicts with your root composer.json require (^9.0.0).

**Comment by MonstreX** [comment]
The package doesn't support medialibrary 9 yet. Will be implemented on the next release.

**Comment by MonstreX** [comment]
v0,95.2: Medialibrary V9 support added.
