### ISSUE TITLE
VE Image

### ISSUE THREAD

**Issue by vortechron** [MonstreX/voyager-extension#29]
Hi , nice package, but how to implement laravel-medialibrary with bread? there is no documentation for me to refer.

**Comment by MonstreX** [comment]
Hello there. 
I didn't get what you meant. Just use a regular field (any type) with VE Image type to store image files. Then use field NAME as a media collection (gallery) NAME to get media data from the media-library (read media-library documentation):
```php
$image = $post->getFirstMedia('field_name');
```

**Comment by engramyosama6** [comment]
@MonstreX Great Library! 

I am facing the same issue here, Can I add imaginary extra field as Image. Or do I need to add a database field for the image which will always be null?

**Comment by MonstreX** [comment]
Thank you!
To add ' VE Image' you have to have DB field (any type). The field name is used as a gallery (media collection) name for the medialibary. It binds the image to the specified model. Yep, the field doesn't have any values inside.
