### ISSUE TITLE
Media Picker no longer works 

### ISSUE THREAD

**Issue by sligregni** [MonstreX/voyager-extension#32]
Hello, 

it seems that [Voyager Media Picker](https://voyager-docs.devdojo.com/bread/introduction-1/media-picker) fields no longer works with Viyager-extension. At lease on my installation. 

These are the steps on fresh installation: 
- Install laravel 8
- Install Voyager v1.5.2
- Install Voyager Extension v0.95.2 

spatie/laravel-medialibrary   version is     9.11.1.

Media folder is still working, but Media Picker field in edit_add bread doesn't  work as show here:

![v-ext](https://user-images.githubusercontent.com/2443573/151028221-06d28d5a-e689-4b58-8897-4bc90a850e46.png)

Is something I can fix? 

Thanks,
Simone

**Comment by MonstreX** [comment]
Seems the media-picker field does not compatible with the new add-edit template. It depends on a Vue component (used in media-picker) which loads twice while overriding the original add-edit template. I didn't find yet the way how to fix it.

**Comment by krausenspb** [comment]
This issue not fixed yet?
Same trouble when 'legacy_edit_add_bread' => false,


    laravel 10.10
    Voyager v1.7
    Voyager Extension v0.95.84

**Comment by MonstreX** [comment]
Nope. "the media-picker field does not compatible with the new add-edit template".
