### ISSUE TITLE
Error `$page_slug` when using custom controller

### ISSUE THREAD

**Issue by lamualfa** [MonstreX/voyager-extension#35]
The error below occurs when I tried to use the voyager custom controller. I set up the voyager custom controller using `php artisan voyager:controller`. I don't change any other controller except for the `VoyagerAuthController`. For more specific information about what I do, I just followed this [tutorial](https://medium.com/development-experiences/custom-voyager-admin-login-with-recaptcha-in-laravel-24630245cd) to set up ReCaptcha in voyager admin login.

Everything is fine until I visited the `add` & `edit` pages. `browse`, `login` & `bread edit` work fine.

![image](https://user-images.githubusercontent.com/39755201/154416663-1c9fa856-a187-4b2e-96ca-334373a6f9f1.png)

**Comment by MonstreX** [comment]
Thank you for reporting. Its kind of issue and I'm gonna fix it in next release. However, currently you can fix it changing your new voyager controller files. Like this:

In app/Http/Controllers/Voyager/VoyagerBaseController.php replace:
**use TCG\Voyager\Http\Controllers\VoyagerBaseController as BaseVoyagerBaseController;**
with:
**use MonstreX\VoyagerExtension\Controllers\VoyagerExtensionBaseController as BaseVoyagerBaseController;**

```php
<?php
namespace App\Http\Controllers\Voyager;

use MonstreX\VoyagerExtension\Controllers\VoyagerExtensionBaseController as BaseVoyagerBaseController;

class VoyagerBaseController extends BaseVoyagerBaseController
{
    //
}
```

**Comment by lamualfa** [comment]
Thank you very much @MonstreX
