### ISSUE TITLE
How to resize uploaded photos

### ISSUE THREAD

**Issue by edge104** [MonstreX/voyager-extension#39]
In which file can I use registerMediaConversions() to resize uploaded photos ?

**Comment by MonstreX** [comment]
Voyager Extension uses as is the original Medialibrary package. It means you have to read Medialibary documentation to solve your needs and handle all Medialibrary functionality. VE uses only limited options like add, remove, and sort media items using the Medialibrary package.
Read this: https://spatie.be/docs/laravel-medialibrary/v10/converting-images/defining-conversions#content-using-model-properties-in-a-conversion

**Comment by wlaskovic** [comment]
Is there a solution for showing thumbnail image in the edit of VE Image? My approach is that I'd like to convert the original image, and after upload to delete it, for cleaning up free space.

**Comment by MonstreX** [comment]
Sorry but VE doesn't provide any transformations with loaded images. All mentioned functionality utilizes Media-Library package: https://spatie.be/docs/laravel-medialibrary/v10/converting-images/defining-conversions.
