### ISSUE TITLE
page_slug is wrong

### ISSUE THREAD

**Issue by saimirballeshi** [MonstreX/voyager-extension#41]
https://github.com/MonstreX/voyager-extension/blob/334537757b2910c596cf386458aa54d2be787504/src/Controllers/VoyagerExtensionBaseController.php#L263

you should change the pageslug as below
View::share(['page_slug'=>$slug]);

**Comment by MonstreX** [comment]
Why? The Laravel doc shows exactly the used way:
https://laravel.com/docs/9.x/views
```php
View::share('key', 'value');
```
