### ISSUE TITLE
VE Media Files are not working as well

### ISSUE THREAD

**Issue by lamualfa** [MonstreX/voyager-extension#43]
I've set the `extra_fields` option in JSON Bread Options. But the field input is still the same as the voyager original has. Also, I've installed the `laravel-medialibrary` & follow the migration instruction. But still not working.

![image](https://user-images.githubusercontent.com/39755201/176079300-69a6de90-09d0-418f-b585-a1796eda2008.png)

#### Nothing change?
![image](https://user-images.githubusercontent.com/39755201/176079580-765ee818-9116-4e7d-b3ce-5a075b465889.png)

#### Even if I put an image:
![image](https://user-images.githubusercontent.com/39755201/176079639-562d214d-a030-486e-8eef-6acc0a85b633.png)

#### Migration:
![image](https://user-images.githubusercontent.com/39755201/176079769-e952943c-3224-4deb-b903-e7bea1a08df2.png)

#### Model:
![image](https://user-images.githubusercontent.com/39755201/176079823-d5f5726b-0335-405b-8a57-b8260202e755.png)

### Tech stack

- Laravel 9
- MYSQL
- The latest Voyager extension
- Laravel media library 10

**Comment by MonstreX** [comment]
At first, you should upload selected images. Then you will see the uploaded images with appropriate controls.
![ScreenClip](https://user-images.githubusercontent.com/1912698/176112153-026d7e2a-b6b1-4f87-a84c-b7c135e1f961.png)

**Comment by lamualfa** [comment]
Error when saving the data. It seems that the field with input type `VE Image` doesn't return any value.

![image](https://user-images.githubusercontent.com/39755201/176124137-4a0baa21-4662-46ca-b03a-a44d9e029e7f.png)

#### Bread options

![image](https://user-images.githubusercontent.com/39755201/176124482-6a2163c6-900f-4c4b-bff6-211be90e2268.png)

#### I uploaded an image with name `atm_bersama_logo.png`:
![image](https://user-images.githubusercontent.com/39755201/176125516-0ea0de72-8302-4e46-a0fe-d774857b73a3.png)

I tried to use the `string` & `json` types for the `header_logo_image` column in migration, but both types still give the same error. Am I missing a step?

**Comment by MonstreX** [comment]
It is supposed to be text type with media-files field type (not JSON). Try to set the field in your table to a TEXT type.

**Comment by MonstreX** [comment]
I forget to say, it doesn't matter which type has the field in your table (all related data save into media-table). But (!) it should be set to nullable (!) The field doesn't use indeed, but the name of the field uses as the name of media library. So you can chanhe the field type to tynyint, for example.

**Comment by lamualfa** [comment]
Woah, it works 🤩. Thank you very much.

![image](https://user-images.githubusercontent.com/39755201/176140166-fdada36e-b675-41d2-acac-5adbe3da11d8.png)

Oh, I have one question. Does input type `VE Image` support custom `extra_fields`? Currently, it only has two fields:  `title` & `alt`.

**Comment by MonstreX** [comment]
No problem. And nope, VE Image supports only those 2 fields. I recommend instead using VE Media Files, it is more flexible and extendable.

**Comment by lamualfa** [comment]
I'll close this issue. again, thank you @MonstreX
