### ISSUE TITLE
VE Select Dropdown Tree

### ISSUE THREAD

**Issue by jcalistop** [MonstreX/voyager-extension#45]
I've been trying for a long time and I can't implement the VE Select Dropdown Tree field. Please help.

**Comment by MonstreX** [comment]
It works as mentioned in the documentation:
![image](https://user-images.githubusercontent.com/1912698/184383691-b184340e-f01f-49c7-848e-8018edc4a64b.png)

1) Make a tree table, Categories for the example:
```json
{
    "relationship": {
        "field": "category",
        "key": "id",
        "label": "title"
    }
}
```

2) Add the relation field where you are going to use the tree menu:
![image](https://user-images.githubusercontent.com/1912698/184384480-abe7445a-47c0-4a0d-bbbf-98d3faf88e39.png)

3) Add to the model:
```php
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function categoryId()
    {
        return $this->belongsTo(Category::class);
    }
````

That's it!

![image](https://user-images.githubusercontent.com/1912698/184384786-4c59652a-003e-4d01-a556-b79f6700432c.png)
