### ISSUE TITLE
Promblem in Multiple Checkbox. count(): Argument #1 ($var) must be of type Countable|array

### ISSUE THREAD

**Issue by enkhtulga** [MonstreX/voyager-extension#47]
Hi. There are some fix needed. Please see original issue on Voyager. -> https://github.com/the-control-group/voyager/issues/5478

Solution (PR) -> https://github.com/the-control-group/voyager/pull/5473

Thank you very much.

**Comment by enkhtulga** [comment]
Until this bug is being fixed, i will use config `'legacy_browse_bread' => true`

**Comment by MonstreX** [comment]
Thank you! 
Has been fixed and released.
