### ISSUE TITLE
Multi Select Edit json_decode(): Argument #1 ($json) must be of type string, array given

### ISSUE THREAD

**Issue by BenWallmeyer** [MonstreX/voyager-extension#48]
i use voyager-extension 0.95.2

If i add Multiselect and add some Option like this
{
    "default": "",
    "options": {
        "monday": "Montag",
        "tuesday": "Dienstag",
        "wednesday": "Mittwoch",
        "thursday": "Donnerstag",
        "friday": "Freitag",
        "saturday": "Samstag",
        "sunday": "Sonntag"
    }
}

save add a new entry and than edit json_decode(): Argument #1 ($json) must be of type string, array given comes. If i use legacy Mode for Edit it will work.

This is already solved in https://github.com/the-control-group/voyager/issues/2207

**Comment by MonstreX** [comment]
I found only one way to fix it. You can do it on your own.
1) Copy original view select_multiple.blade.php from voyager into the folder inside app view -> **/resources/views/vendor/voyager/formfields/select_multiple.blade.php**
2) Make the fix - change one line.
replace:
```php
$dataTypeContent->{$row->field} = json_decode($dataTypeContent->{$row->field})
```
with:
```php
$dataTypeContent->{$row->field} =  is_array($dataTypeContent->{$row->field})?
                  $dataTypeContent->{$row->field} :
                  json_decode($dataTypeContent->{$row->field});
```

**Comment by BenWallmeyer** [comment]
Work with update

**Comment by BenWallmeyer** [comment]
I tried have also latest laravel version and also test to isntall latest voyager version this is also not a problem but if I installed the latest voyager-extension there are a lot of dependencies which must be solved before.


Von: Yuriy Ovdeyev ***@***.***>
Gesendet: Donnerstag, 8. September 2022 18:07
An: MonstreX/voyager-extension ***@***.***>
Cc: BenWallmeyer ***@***.***>; Author ***@***.***>
Betreff: Re: [MonstreX/voyager-extension] Multi Select Edit json_decode(): Argument #1 ($json) must be of type string, array given (Issue #48)


I've just checked it out. It works. I used the latest versions laravel, voyager, and voyager-extension.
