### ISSUE TITLE
Inline Edit Role

### ISSUE THREAD

**Issue by BenWallmeyer** [MonstreX/voyager-extension#49]
If i disable Edit for an user Role than Inline Edit is not disabled. 

How to do this.

**Comment by MonstreX** [comment]
I didn't get what you mean. How can I reproduce this?

**Comment by BenWallmeyer** [comment]
Please set to any bread for normal User only add and read not edit. Than in bread set one column inline edit.

The User cannot edit entry but inline edit will work. That it the Problem

**Comment by MonstreX** [comment]
Yep, it is. You are right. Fixed, you can find the fixed file on the updated repository.
https://github.com/MonstreX/voyager-extension/blob/master/resources/views/bread/browse-list.blade.php

**Comment by BenWallmeyer** [comment]
Yeah works i override with my file.  Please make a new Release for update with composer
