### ISSUE TITLE
VE Inline Field set - Media type required message is showing when media was already set.

### ISSUE THREAD

**Issue by enkhtulga** [MonstreX/voyager-extension#51]
in BREAD, i have set `atts` to `required: true` config:
<img width="388" alt="Screen Shot 2022-10-07 at 09 26 27" src="https://user-images.githubusercontent.com/6397097/194447112-530822de-e611-43b5-bccf-6b030b9269ef.png">

In form:
<img width="661" alt="Screen Shot 2022-10-07 at 09 26 12" src="https://user-images.githubusercontent.com/6397097/194447035-890e598e-7d3f-4b01-b0ff-ae00dbb68ca6.png">

Problem:
I have already uploaded media image. Unfortunately required validation is still showed empty. How to handle it?

**Comment by MonstreX** [comment]
Sorry, this kind of field doesn't work with the attribute 'required' as you are supposed to in the case when you have already linked media files. Just remove the 'require' attribute for this field.

**Comment by enkhtulga** [comment]
What i want to do is set required to media file. Is it possible? Is there any option for it? Thank you.

**Comment by MonstreX** [comment]
I've got what you meant, but currently, this feature doesn't work for this kind of field (media files).
