### ISSUE TITLE
TineMCE doesn't work

### ISSUE THREAD

**Issue by battulga0719** [MonstreX/voyager-extension#53]
![error](https://user-images.githubusercontent.com/63037225/200219124-f6e03795-400f-4b13-af0d-b2a1c93ad60a.PNG)

**Comment by BenWallmeyer** [comment]
Same here,
if we use without this ectension TineMCE is working, with the extension same error.

**Comment by MonstreX** [comment]
How can I reproduce this error?

**Comment by BenWallmeyer** [comment]
make a Text Database Field, Open Bread and set field to Rich Text Box and than open. Normally there msut come TineMCE Editor

![1](https://user-images.githubusercontent.com/8560832/204198790-e63a598b-c4e6-4f42-be6d-a702df5016e5.png)
![2](https://user-images.githubusercontent.com/8560832/204198808-9a1bdb01-9666-4144-87b7-3a86963bb98c.png)

**Comment by MonstreX** [comment]
Unfortunately, changing settings (after init an instance) doesn't work anymore in the new version of TinyMCE. These settings will remove on the next release of VE. As a hotfix, you can remove the function 'tinymce_setup_callback' in the js.blade.php file.

**Comment by BenWallmeyer** [comment]
Ok with override it works. Thx for support
