### ISSUE TITLE
Call to undefined method TCG\Voyager\Models\Page::getMedia()

### ISSUE THREAD

**Issue by uvarovdev** [MonstreX/voyager-extension#59]
Hi. I'm getting `Call to undefined method TCG\Voyager\Models\Page::getMedia()` error when try to create or edit page.
Can you help a bit?

**Comment by MonstreX** [comment]
Hello there. Seems your forget to prepare the model to use media-library methods. This may help you::
https://spatie.be/docs/laravel-medialibrary/v10/basic-usage/preparing-your-model

**Comment by uvarovdev** [comment]
I've prepared Voyager page model and it works now.
Anyway thank you for your help!=)

*It was my mistake to install voyager-site over voyager with dummy. Clean installation fixed this issue.

**Comment by MonstreX** [comment]
Okay, no problem)
