### ISSUE TITLE
Media Picker not working

### ISSUE THREAD

**Issue by SWEET1S** [MonstreX/voyager-extension#62]
Hello, I noticed a strange bug. When legacy_edit_add_bread is set to false in the voyager extension, the Voyager media picker does not work. If set to true, that is, use the default edit-add.blade.php, then everything works. How to fix to use edit-add from you and not from Voyager?

**Comment by SWEET1S** [comment]
![image](https://user-images.githubusercontent.com/84906111/223539325-b55d1e34-a470-4be2-808e-7d633599f8ca.png)
The problem is that this particular button does not work. That is, when pressed, it does not work.

**Comment by MonstreX** [comment]
"Seems the media-picker field does not compatible with the new add-edit template. It depends on a Vue component (used in media-picker) which loads twice while overriding the original add-edit template. I didn't find a way how to fix it.."
https://github.com/MonstreX/voyager-extension/issues/32
