### ISSUE TITLE
How to translate VE fields?

### ISSUE THREAD

**Issue by SWEET1S** [MonstreX/voyager-extension#63]
![image](https://user-images.githubusercontent.com/84906111/223840695-24e238a1-ca2e-4bd5-9fd9-0260afce7381.png)
As I noticed Translation fields cannot be VE Fields Group. How to make trait Translatable work on VE components, so to speak?

**Comment by SWEET1S** [comment]
Sorry, I didn't notice that VE Field doesn't support translatable.

**Comment by MonstreX** [comment]
There is only one way to translate - using built-in helpers. 
https://github.com/MonstreX/voyager-extension#localizations
