### ISSUE TITLE
How to make the extension obey a new name other than /admin?

### ISSUE THREAD

**Issue by locopine** [MonstreX/voyager-extension#65]
For some time now I've been trying to get around an inconvenience that has been happening, with the "assets" path, when using the extension. Can you "give me a light" on how to make the extension accept the change from "/admin" to "/backend" made in "/config/voyager.php"?

I found this part:

```
// vendor/monstrex/voyager-extension/src/Controllers/VoyagerExtensionController.php:244
// vendor/monstrex/voyager-extension/src/Controllers/VoyagerExtensionController.php:268
/*
  * Return content of the requested asset file (js, css and etc)
  *
  * input: 'http://site.com/admin/voyager-extension/path/to/assets/file.*'
  */
```

however, according to my "somewhat limited" knowledge, in terms of Monstrex extension, it appears to be plastered!
I tried something like in the code below and it partially solves it. But something in the javascript doesn't recognize the change!

```
<?php
// vendor/monstrex/voyager-extension/routes/routes.php

Route::group(['prefix' => config('voyager.user.redirect')], function () {
    // Route::group(['prefix' => 'admin'], function () {
    Route::group(['as' => 'voyager.'], function () {
        $extensionController = '\MonstreX\VoyagerExtension\Controllers\VoyagerExtensionController';
        //Load translations
       ...
```

Any help is welcome.

Tks.

**Comment by MonstreX** [comment]
Thank you for your request. I've made some modifications, so try to use the latest release v0.95.81, and the new config parameter in config/voyager-extension.php:  
```php
'assets_path_prefix' => 'backend',
````

**Comment by locopine** [comment]
Thanks for your solution! I updated to v0.95.81 and it worked perfectly.

Only one thing still intrigues me; all requests, except for "voyager-extension" work within the "Force HTTPS" parameters that I defined. Do you have any ideas on how plugin requests can handle the settings and I can get rid of the CORS error?

**Comment by locopine** [comment]
> Thanks for your solution! I updated to v0.95.81 and it worked perfectly.
> 
> Only one thing still intrigues me; all requests, except for "voyager-extension" work within the "Force HTTPS" parameters that I defined. Do you have any ideas on how plugin requests can handle the settings and I can get rid of the CORS error?

Possible solution (it worked for my case) is below:

```
    // ...
    // vendor/monstrex/voyager-extension/src/VoyagerExtensionServiceProvider.php

    /**
     * Define your route model bindings, pattern filters, etc.
     *
     * @return void
     */
    public function boot()
    {

        // include conditional "URL::forceScheme('https')" for production environment
        if (env('APP_ENV') === 'production') {
            \Illuminate\Support\Facades\URL::forceScheme('https');
        }

        // ...
```

As changes are not indicated directly in the installed package (vendor) it would be great if it were incorporated in the source or in the "config" optionally so that it needs implementation. 

Much obliged.
