### ISSUE TITLE
there is many issues related to the image 

### ISSUE THREAD

**Issue by hussainabuhajjaj** [MonstreX/voyager-extension#66]
in case of the image is not null and trying to update the record it returns SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'image' cannot be null

in case of trying to clone image 
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'image' cannot be null

**Comment by MonstreX** [comment]
Describe in detail how to reproduce this issue pls.
