### ISSUE TITLE
Update for new version of Voyager

### ISSUE THREAD

**Issue by lamtin222** [MonstreX/voyager-extension#71]
Dear MonstreX,
Please update code for version : "dev-1.6-l10" of voyager. tks

**Comment by MonstreX** [comment]
Sorry, but project support is focused exclusively on release versions. Not any DEV versions.

**Comment by hazbu** [comment]
> Sorry, but project support is focused exclusively on release versions. Not any DEV versions.

Now voyager 1.7 has released, its stable version and support laravel 10

**Comment by MonstreX** [comment]
The release of the new version has been published.
