### ISSUE TITLE
voyager-extension-translations:1 404

### ISSUE THREAD

**Issue by BenWallmeyer** [MonstreX/voyager-extension#75]
Hey i got an 404

Failed to load resource: the server responded with a status of 404 () voyager-extension-translations:1

**Comment by BenWallmeyer** [comment]
OK it works. You must create a new config file.

**Comment by jonathanribas** [comment]
Hi @BenWallmeyer, do you mean using this config file https://github.com/MonstreX/voyager-extension?tab=readme-ov-file#config-file?
Thanks in advance!
