### ISSUE TITLE
browse_tree is not working

### ISSUE THREAD

**Issue by cosmokit** [MonstreX/voyager-extension#76]
Hi!

I have a table 'product_categories' with fields:
```
id
parent_id
slug
title

```
I've tried to put {"browse_tree": true} into parent_id Optional Details, extra options fields and even into relationship details.
And nothing happens. 

Am i doing something wrong? 

![image](https://github.com/MonstreX/voyager-extension/assets/71525626/67602abb-1fbe-4da0-b243-b4aade91311c)

**Comment by MonstreX** [comment]
There is no need to make a relationship. Only adding {"browse_tree": true} into pareant_id is enough - that's it (without relationship option!). When you add a relationship it changes the logic for the template rendering in that field.

**Comment by cosmokit** [comment]
yeap. you're right. thanks!
