### ISSUE TITLE
Mixed Content: Voyager extension Assets issue after SSL configuration

### ISSUE THREAD

**Issue by enkhtulga** [MonstreX/voyager-extension#78]
Hello, Thank you for an awesome extension of Voyager Admin.

I have faced the following issue after SSL configuration. How to solve it? @MonstreX  Thank you!
```
Mixed Content: The page at 'https://domain.com/admin/faqs' was loaded over HTTPS, 
but requested an insecure script 'http://domain.com/admin/voyager-extension-assets?path=js%2Fapp.js'. 
This request has been blocked; the content must be served over HTTPS.
```

**Comment by MonstreX** [comment]
Hello, thanks.
The issue is not about Voyager or Voyager Extension, Inside they both utilize Laravel route() helper. See your configuration in general.

**Comment by enkhtulga** [comment]
Excuse me. I don't understand. Can you please provide me further information?

Voyager assets work fine.
```
<link rel="stylesheet" href="https://domain.com/admin/voyager-assets?path=css%2Fapp.css">
```
Voyager Extension has no https:
```
<link rel="stylesheet" type="text/css" href="http://domain.com/admin/voyager-extension-assets?path=css%2Fapp.css">
```

**Comment by MonstreX** [comment]
Sorry, I have no idea what's wrong with your web server configuration. VE utilizes the Laravel helper route() to create a link.  What kind of protocol (http or https) - the route() helper responsibility. VE does not change http or https. I have a few dozen web sited with SSL and no one has this issue.
