### ISSUE TITLE
It is possible with voyager-extension to add another "level" to a select?

### ISSUE THREAD

**Issue by repogesyco** [MonstreX/voyager-extension#80]
Hello, Thank you for an awesome extension of Voyager Admin.

It is possible with voyager-extension to add another "level" to a select, for example by adding the letters select to val1.
But in certain cases that second select can be of another type, a check or another type of component, if so how could it be done, thank you.

{
    "inline_set": {
        "source": "App\\Models\\Meta",
        "many": true,
        "columns": 2,
        "fields": {
            "date": {
                "label": "Date",
                "type": "date"
            },
            "select": {
                "label": "Select",
                "type": "select",
                "options": {
                    "val1": {
                        "label": "Option One",
                        "type": "select",  // This is what I would like to add. This is what I would like to add, the letters option.
                        "options": {
                            "a": "A",
                            "b": "B",
                            "c": "C"
                        },
                        "default": "a"
                    },
                    "val2": "Option Two",
                    "val3": "Option Three"
                },
                "default": "val3"
            },
            "number": {
                "label": "Number",
                "type": "number",
                "attrs": {
                    "required": true
                }                
            },
            "checkbox": {
                "label": "Checkbox",
                "type": "checkbox",
                "on": "Enabled",
                "off": "Disabled",
                "default": "on"
            },
            "radio": {
                "label": "Radio",
                "type": "radio",
                "options": {
                    "center": "Center",
                    "left": "Left",
                    "right": "Right"
                },
                "default": "left"
            },
            "image": {
                "label": "Image",
                "type": "media",
                "remove_delay": 5000
            },
            "rich_text": {
                "label": "Rich Text Box",
                "type": "richtext",
                "min_height": 150
            },
            "code": {
                "label": "Ace Editor",
                "type": "code",
                "mode": "html",
                "theme": "monokai",
                "minlines": 3,
                "maxlines": 20
            },
            "seo_title": {
                "label": "Title",
                "type": "text",
                "class": "col-md-12",
                "attrs": {
                    "required": true     
                }
            },
            "meta_description": {
                "label": "Description",
                "type": "textarea",
                "class": "col-md-6"
            },
            "meta_keywords": {
                "label": "Keywords",
                "type": "textarea",
                "class": "col-md-6"
            }
        }
    }
}

**Comment by MonstreX** [comment]
Sorry, but development of the project has been temporarily suspended.
