### ISSUE TITLE
Media Picker still no works

### ISSUE THREAD

**Issue by krausenspb** [MonstreX/voyager-extension#86]
Hello,

it seems that Voyager Media Picker fields no works with Voyager-extension. At lease on my installation.

These are the steps on fresh installation:

    laravel 10.10
    Voyager v1.7
    Voyager Extension v0.95.84
    'legacy_edit_add_bread' => false,

Media section is working, but Media Picker field in edit_add bread doesn't work as show here:
![image](https://github.com/MonstreX/voyager-extension/assets/17198710/937abc68-835c-43d2-b3a2-6b353c876eae)

Is something I can fix?

Thanks,

_Originally posted by @krausenspb in https://github.com/MonstreX/voyager-extension/issues/32#issuecomment-2147755098_

**Comment by MonstreX** [comment]
The media-picker field does not compatible with the new add-edit template. Development of the project has been temporarily suspended.
